### ISSUE TITLE
BulkProcessor doesn't respect the -DbatchSize

### ISSUE THREAD

**Issue by magaldima** [erfangc/elasticsearch-performance-testing#1]
The BulkProcessor gets initialized with a bulkSize in MB. Depending on the size of each docs (based on the number of columns), each batch can be composed of a different number of docs. I noticed when increasing the -DbatchSize to 20MB, each batch was capped at 1000 docs no matter what. I think in order to respect the bulkSize() parameter, the bulkActions() parameter needs to be set to -1.

**Comment by erfangc** [comment]
PR it up
